# This is a basic workflow to help you get started with Actions

name: Auto Release

on:
  push:
    branches: [ "master"]

jobs:
  release:
    name: Create Release Job
    permissions: write-all
    runs-on: windows-latest

    # strategy:
    #   matrix:
    #     node-version: [18.x]


    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      
      - name: Install Dependencies
        run: npm install

      - name: Create Release
        id: release
        env:
          HUSKY: 0
          GH_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
        run: npm run release
